version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"