name: Question 🤷‍♂️
description: Got a question about GPT-Computer-Agent, deployment, development or usage?
title: '[QUESTION] <title>'
labels: ['🤷‍♂️ Question']
assignees:
  - NxPkg

body:
  # Filed 1 - Intro Text
  - type: markdown
    attributes:
      value: >
        Thanks for using GPT-Computer-Agent! Questions are welcome, but in the future will be moving over to
        [Discussions](https://github.com/khulnaSoft/gpt-computer-agent/discussions) page.
        Quick questions should be asked [here](https://github.com/khulnaSoft/gpt-computer-agent/discussions/148) instead.
    validations:
      required: false

  # Field 2 - The actual question
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Outline your question in a clear and concise manner
    validations:
      required: true

  # Field 3 - Category
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What part of the application does this relate to?
      options:
        - Setup and Deployment
        - Configuration
        - App Usage
        - Development
        - Documentation
        - Alternate Views
        - Authentication
        - Using Icons
        - Widgets
        - Actions
        - Language Support
        - Search & Shortcuts
        - Status Checking
        - Theming & Layout
    validations:
      required: true

  # Field 4 - User has RTFM first, and agrees to code of conduct, etc
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: Before submitting, please ensure that
      options:
        - label: You are using a [supported](https://github.com/khulnaSoft/gpt-computer-agent/blob/master/.github/SECURITY.md#supported-versions) version of GPT-Computer-Agent (check the first two digits of the version number)
          required: true
        - label: You've checked that this [question hasn't already been raised](https://github.com/khulnaSoft/gpt-computer-agent/issues?q=is%3Aissue)
          required: true
        - label: You've checked the [docs](https://github.com/khulnaSoft/gpt-computer-agent/tree/master/docs#readme) and [troubleshooting](https://github.com/khulnaSoft/gpt-computer-agent/blob/master/docs/troubleshooting.md#troubleshooting) guide
          required: true
        - label: You agree to the [code of conduct](https://github.com/khulnaSoft/gpt-computer-agent/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
          required: true
