# model/tokenizer
model_name: "tiiuae/falcon-7b"
tokenizer_name: "tiiuae/falcon-7b"
gradient_checkpointing: true
save_name: "nomic-ai/gpt4all-falcon"

# dataset
streaming: false
num_proc: 64
dataset_path: "nomic-ai/gpt4all-j-prompt-generations"
revision: "v1.3-groovy"
max_length: 1024
batch_size: 32

# train dynamics
lr: 2.0e-5
min_lr: 0 
weight_decay: 0.0
eval_every: 500
eval_steps: 105
save_every: 1000
log_grads_every: 500
output_dir: "ckpts/falcon"
checkpoint: "/home/paperspace/gpt4all/ckpts/mpt/step_1000"
lora: false
warmup_steps: 500
num_epochs: 2 

# logging
wandb: true
wandb_entity: "gpt4all"
wandb_project_name: "gpt4all"
seed: 42

