name: Custom Package

on:
  workflow_dispatch: 


permissions:
  packages: write      


concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true
jobs:
  windows:
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[default]
          pip install .[agentic]
          pip install embedchain[poe]
          pip install pyinstaller

        
      - name: Run PyInstaller
        run: |
          pyinstaller app.spec
          mv dist/GPT_Computer_Agent.exe GPT_Computer_Agent_windows.exe
        
      # Upload as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: GPT_Computer_Agent_windows.exe


  macos:
    runs-on: macos-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[default]
          pip install .[agentic]
          pip install embedchain[poe]
          pip install pyinstaller

        
      - name: Run PyInstaller
        run: |
          pyinstaller app.spec
          mv dist/GPT_Computer_Agent GPT_Computer_Agent_macos
        
      # Upload as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: GPT_Computer_Agent_macos
