name: Custom Package

on:
  workflow_dispatch: 

permissions:
  packages: write      

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.11

      # Add caching step here
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup_package.py', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[default]
          pip install .[agentic]
          pip install cx_Freeze

      - name: Run cx_Freeze
        run: |
          python setup_package.py build
        
      - name: Zip the build
        run: |
          7z a GPT_Computer_Agent_windows.zip build/exe.win-amd64-3.11/*

      - name: Artifact the build
        uses: actions/upload-artifact@v4
        with:
          name: GPT_Computer_Agent_windows
          path: GPT_Computer_Agent_windows.zip
