name: Latest Changes

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # To allow latest-changes to commit to master
          token: ${{ secrets.ORG_REPO_TOKEN }}
      - uses: khulnasoft/latest-changes@0.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
