# This workflow enables developers to call PR-Assistants `/[actions]` in PR's comments and upon PR creation. 
# Learn more at https://www.khulnasoft.com/pr-assistant/
# This is v0.2 of this workflow file

name: PR-Assistant

on:
 pull_request:
 issue_comment:
 workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_assistant_job:
    runs-on: ubuntu-latest
    name: Run pr assistant on every pull request
    steps:
      - name: PR Assistant action step
        id: prassistant
        uses: khulnasoft/pr-assistant@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }} # optional
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PINECONE.API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE.ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
